// TODAS AS VARIAVEIS DEVEM POSSUIR IDENTIFICADORES EXCLUSIVOS
// VARIAVEIS DEVEM COMECAR COM UMA LETRA OU COM $ _ 
// VARIAVEIS NAO DEVEM TER O MESMO NOME DE PALAVRAS RESERVADAS
// JS EH CASE SENSITIVE 

"use strict"; //GARANTE QUE O MEU CODIGO EXECUTE DE FORMA EXCLUSIVA COM REGRAS ADICIONAIS
{
  // VARIAVEIS NAO DECLARADAS
  x = 5;
  y = 6;
  z = x + y;
}

{
  // VARIAVEIS DECLARADAS SEM ESCOPO DE BLOCO E ALTERAVEIS
  var x = 5;
  var y = 6;
  var z = x + y;  
}

{
  // VARIAVEIS DECLARADAS COM ESCOPO DE BLOCO E ALTERAVEIS
  let x = 5;
  let y = 6;
  let z = x + y;  
}

{
  // VARIAVEIS DECLARADAS COM ESCOPO DE BLOCO E INALTERAVEIS
  const x = 5;
  const y = 6;
  const z = x + y;  
}

// VARIAVEL UNDEFINED
let timeFutebol;

// MULTIPLAS DECLARACOES
let timeTenisMesa = 'Dusseldorf', timeBasquete = 'Corinthians';

// UTILIZADO PARA DECLARAR A VARIAVEL COMO SENDO PRIVADA
const _id = 1;